### ISSUE TITLE
Status badge

### ISSUE THREAD

**Issue by abbott567** [dwpdigitaltech/design-examples#6]
**_Screenshot_**

<img width="299" alt="status" src="https://user-images.githubusercontent.com/9450064/34210361-77d8be9e-e58d-11e7-93ac-1b7e998398d1.png">

**_What problem does this design solve?_**
A quick way to show agents the status of the claim they are working on.

**_Which service are you researching this design on?_**
- Bereavement Support Payment - The badges are in the production build of the payment scheduler, and we are continuing with the same format in the prototypes for the claim management.

**_How have you approached the design?_**
The design is a combination of the GOVUK .x-large heading, GOVUK subheading and the badge which was taken from [companies house](https://beta.companieshouse.gov.uk/company/10344843/officers).

**_What have you learned from research?_**
The original design was plain text but it went unnoticed by most agents we tested with. Since adding the colours the agents were able to quickly recognise the status of the claim.

**_Have you tested this for accessibility?_**
- It has been tested with users of JAWS, Dragon, Zoomtext, and Read and Write Gold. This is both agents on their work devices and the DWP accessibility compliance team.

**Comment by htmlandbacon** [comment]
Closing in favour of #9
